//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkCodeFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public string Id { get; set; }
        public Nullable<int> Note1 { get; set; }
        public string Materials { get; set; }
        public int NoteId { get; set; }
    }
}
